[clash-party]
src.github = "mihomo-party-org/clash-party"
include_regex = "^v.*"
prefix = "v"
fetch.url = "https://github.com/mihomo-party-org/clash-party/releases/download/v$ver/mihomo-party-linux-$ver-amd64.deb"

[ww-manager]
src.github = "timetetng/wutheringwaves-cli-manager"
include_regex = "^v\\d.*"
prefix = "v"
fetch.github = "timetetng/wutheringwaves-cli-manager"
