# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clash-party = {
    pname = "clash-party";
    version = "1.9.6";
    src = fetchurl {
      url = "https://github.com/mihomo-party-org/clash-party/releases/download/v1.9.6/mihomo-party-linux-1.9.6-amd64.deb";
      sha256 = "sha256-n8FUF0Mur6UdrSEhf1V8XEsCkvgU52/9xqRTpFH1geo=";
    };
  };
  ww-manager = {
    pname = "ww-manager";
    version = "hpatchz-v4.8.0";
    src = fetchFromGitHub {
      owner = "timetetng";
      repo = "wutheringwaves-cli-manager";
      rev = "hpatchz-v4.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-mOmmpeQVsx7XzYVWcwon1AZCDWJC6pqIb3X4vyQgaRI=";
    };
  };
}
